// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebAPI.Data;

#nullable disable

namespace TestWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240308160932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestWebAPI.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CareatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("UAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareatedDate = new DateTime(2024, 3, 8, 21, 39, 30, 838, DateTimeKind.Local).AddTicks(7070),
                            Name = "Test1",
                            Salary = 1000.0,
                            UAN = "ABCD1"
                        },
                        new
                        {
                            Id = 2,
                            CareatedDate = new DateTime(2024, 3, 8, 21, 39, 30, 838, DateTimeKind.Local).AddTicks(7087),
                            Name = "Test2",
                            Salary = 2000.0,
                            UAN = "ABCD2"
                        },
                        new
                        {
                            Id = 3,
                            CareatedDate = new DateTime(2024, 3, 8, 21, 39, 30, 838, DateTimeKind.Local).AddTicks(7090),
                            Name = "Test3",
                            Salary = 3000.0,
                            UAN = "ABCD3"
                        },
                        new
                        {
                            Id = 4,
                            CareatedDate = new DateTime(2024, 3, 8, 21, 39, 30, 838, DateTimeKind.Local).AddTicks(7092),
                            Name = "Test4",
                            Salary = 4000.0,
                            UAN = "ABCD4"
                        },
                        new
                        {
                            Id = 5,
                            CareatedDate = new DateTime(2024, 3, 8, 21, 39, 30, 838, DateTimeKind.Local).AddTicks(7094),
                            Name = "Test5",
                            Salary = 5000.0,
                            UAN = "ABCD5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
